### ISSUE TITLE
Bug in IRLS Algorithm

### ISSUE THREAD

**Issue by kaneplusplus** [bwlewis/GLM#2]
These notes are incredibly useful.

I think I've found a bug though. Check "Algorithm IRLS: Iteratively reweighted least squares estimation" in the "Input" section. I think the line:

Let x_{j+1}=x_j+(A^TWA)^{−1}A^TWz.

should be 

Let x_{j+1}= (A^TWA)^{−1}A^TWz.

**Comment by bwlewis** [comment]
You're right! Thanks. Fixed in  commit 58ea988084f385df50e7030c8a29fea3855ebc3f
